name: Test Project
on:
  push:
     branches:
       - master

jobs:
  test-action:
     runs-on: ubuntu-latest
     steps:
             - name: Run test.py
               run: python /smart_home/measurement/tests.py
                      


